name: 'Comment if files changed'
description: 'Post a reply to comments in PRs if file to which the comment was left has been changed'
inputs:
  repo-token:
    description: 'GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'message-circle'
  color: 'yellow'
